## Data Frames
A data frame is a collection of columns–similar to a spreadsheet or SQL table. Each column has a name at the top that represents a variable, and includes one observation per row.<br>
Data frames helps to summarize data and organize it in a format that is easy to read.
<b> creating a data frame </b>? is done by <b>data.frame()</b> function, it takes vectors as inputs separated by comma and having the column name specified.

In [5]:
df1=data.frame(x=c(1.5,2.6,8), y=c(6,7,8))
df1

x   y
1 1.5 6
2 2.6 7
3 8.0 8

## documentation files
R documentation is a tool that helps you easily find and browse the documentation of almost all R packages on CRAN. It’s a useful reference guide for functions in R code. Let’s go through a few of the most useful functions for working with files. 

<br><br>
we use the <b> dir.create() </b>  function to a new folder , or directory to store our file/.
<br>
We use the <b> file.create() </b> function to create an blank file.<br>

In [8]:
dir.create ("destination_folder")

file.create ("new_text_file.txt") 

file.create ("new_word_file.docx") 

file.create ("new_csv_file.csv") 

file.copy ("new_text_file.txt" , "destination_folder")

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

## Arrays
arrays are very similar to a vector, they just ahev an extra option of dimension added to them that makes them unique.
<u> vectors </u> vectors are one dimensional <br>
<u> arrays </u> are multidimensional.<br>

we use the <b> array() </b> function which takes the a vector and dimensions are passed as a list.

In [15]:
x<-array(c(4,5,2,1),c(2,2))
x
print("or")
v1=c(1,2,3,4,5,6,7,8)
dim=c(4,2)
myarray=array(v1,dim)
myarray

[,1] [,2]
[1,] 4    2   
[2,] 5    1

[1] "or"


[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

## Properties of Arrays
Type of elements does our array contain with the typeof() function.<br>
The structure of the array with the str() function.<br>
Other attributes with the attributes() function.<br>

<BR>
    

## MATRICES
A Matrix is a vector that also contains information on the number of rows and number of columns. However vectors are not matrices. <br>
to create a matrix we use <b> matrix() </b> function as shown

In [19]:
x <- c(1,2,3,4)
mat <- matrix(x, nrow=2, ncol=2, byrow=TRUE)
mat
print("the byrow=TRUE means the matrix will be filled by the row, it is not the same as if we do not fill it by row")

mat2 <- matrix(x, nrow=2, ncol=2, byrow=FALSE)
mat2

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[1] "the byrow=TRUE means the matrix will be filled by the row, it is not the same as if we do not fill it by row"


[,1] [,2]
[1,] 1    3   
[2,] 2    4

<b>Matrix Operations</b>
<br> multiplication

In [20]:
mat * mat2


[,1] [,2]
[1,] 1     6  
[2,] 6    16

transpose

In [21]:
t(mat)


[,1] [,2]
[1,] 1    3   
[2,] 2    4